[0m01:43:22.970362 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98b5b7e0b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98b4b95c30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98b4b95c90>]}


============================== 01:43:22.972022 | c3cfdff2-a9a3-4014-9d1c-4c62aec7bfd7 ==============================
[0m01:43:22.972022 [info ] [MainThread]: Running with dbt=1.9.3
[0m01:43:22.972279 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/granite/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m01:43:22.975129 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/granite/.dbt')}
[0m01:43:22.975328 [info ] [MainThread]: Creating dbt configuration folder at 
[0m01:43:32.554730 [debug] [MainThread]: Starter project path: /home/granite/.local/lib/python3.10/site-packages/dbt/include/starter_project
[0m01:43:32.556720 [info ] [MainThread]: 
Your new dbt project "intus_windows_assignment" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m01:43:32.557081 [info ] [MainThread]: Setting up your profile.
[0m01:43:36.760198 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m01:43:36.760476 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m01:44:08.148332 [error] [MainThread]: Encountered an error:

[0m01:44:08.150006 [error] [MainThread]: Traceback (most recent call last):
  File "/home/granite/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/granite/.local/lib/python3.10/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/granite/.local/lib/python3.10/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/home/granite/.local/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/granite/.local/lib/python3.10/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/granite/.local/lib/python3.10/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/granite/.local/lib/python3.10/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/home/granite/.local/lib/python3.10/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
  File "/usr/lib/python3/dist-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
  File "/usr/lib/python3/dist-packages/click/termui.py", line 150, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m01:44:08.151033 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 42.698074, "process_in_blocks": "21880", "process_kernel_time": 0.043274, "process_mem_max_rss": "98404", "process_out_blocks": "80", "process_user_time": 0.714026}
[0m01:44:08.151379 [debug] [MainThread]: Command `dbt init` failed at 01:44:08.151324 after 42.70 seconds
[0m01:44:08.151574 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98b5b7e0b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98b4172140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98b4172dd0>]}
[0m01:44:08.151802 [debug] [MainThread]: Flushing usage events
